Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [17]:
import numpy as np
x = int(input('Введите количество элементов: '))
np.arange(x-1,-1,-1)

Введите количество элементов: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [2]:
?np.arange

Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [18]:
import numpy as np
N = int(input('Введите количество элементов диагональной матрицы: '))
N_matrix = np.diag(np.arange(N), k=0)
print(N_matrix)
matrix_diag_sum = sum (np.diag(N_matrix))
print("Сумма значений по диагонали равна ", matrix_diag_sum)

Введите количество элементов диагональной матрицы: 5
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]
Сумма значений по диагонали равна  10


Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [24]:
a = np.array( [[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array( [4, 12, -3])

In [25]:
type(a)


numpy.ndarray

In [26]:
type(b)

numpy.ndarray

In [27]:
from numpy import linalg

In [28]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [29]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True